service: aws-node-express-api-project
frameworkVersion: '3'

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs18.x
  iam:
    role:
      managedPolicies:
        - "arn:aws:iam::aws:policy/AmazonS3FullAccess"
  httpApi:
    cors: true

functions:
  api:
    handler: dist/index.handler
    events:
      - httpApi: '*'
